version: '3.1'
services:
  stats-server:
    build: stats-service/stats-server
    image: stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - STATS_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats-db
      - SERVER_PORT=9090
      - STATS_DB_HOST=stats-db
      - STATS_DB_PORT=5432
      - STATS_DB_NAME=stats-db
      - STATS_DATASOURCE_USERNAME=root
      - STATS_DATASOURCE_PASSWORD=root
      - STATS_SERVER_URL=http://stats-server:9090

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  ewm-service:
    build: ewm-service
    image: ewm-service
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - MAIN_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm-db
      - STATS_SERVER_URL=http://stats-server:9090
      - SERVER_PORT=8080
      - DB_HOST=ewm-db
      - DB_PORT=5432
      - DB_NAME=ewm-db
      - MAIN_DATASOURCE_USERNAME=root
      - MAIN_DATASOURCE_PASSWORD=root
  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewm-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root